/**
 * Electron auto-updater (binary shell).
 *
 * Uses electron-updater's "generic" provider pointing at the Hono server's
 * `/api/electron/shell` endpoint. The Hono route serves `latest-mac.yml` /
 * `.dmg` / `.zip` etc. by 302-redirecting to presigned S3 URLs (see
 * `examples/server-hono/examples/server-hono/server/routes/electron-shell.ts`).
 *
 * Lifecycle:
 *   - autoDownload = false  → user has to confirm via `updater:download` IPC
 *   - autoInstallOnAppQuit = true → applies the downloaded update on next quit
 *   - Periodic re-check every 1h
 *   - Startup check with three retries (10s, 30s, 90s) so a transient
 *     failure on launch doesn't permanently disable updates for that session
 *
 * Renderer side: lib/hooks/useElectronUpdater.ts subscribes to
 * `updater:status` events and exposes the install button to the user.
 */

import { autoUpdater, type UpdateInfo } from 'electron-updater';
import { BrowserWindow, ipcMain, app, net } from 'electron';
import * as path from 'path';
import * as fs from 'fs';

let mainWindow: BrowserWindow | null = null;
let _periodicInterval: ReturnType<typeof setInterval> | null = null;
let _disabled = false;

const PERIODIC_CHECK_MS = 60 * 60 * 1000;
const RETRY_DELAYS_MS = [10_000, 30_000, 90_000];

/**
 * Skip automatic update checks when the machine reports no network. Surfacing
 * an `error` status from a fetch the user already knows can't succeed (the
 * offline indicator is visible) is noise — we silently no-op instead and let
 * `triggerOnlineRecheck()` fire a fresh check on the next offline → online
 * transition (wired from `setupNetworkMonitoring` in main/index.ts).
 */
function isOffline(): boolean {
  return !net.isOnline();
}

/** Called from setupNetworkMonitoring when net.isOnline() flips false → true. */
export function triggerOnlineRecheck(): void {
  if (_disabled) return;
  console.log('[updater] online again — triggering update check');
  autoUpdater.checkForUpdates().catch((err: Error) => {
    console.error('[updater] online-recheck failed:', err.message);
  });
}

/** Strip URLs from error messages before surfacing them in the UI. The shell
 *  feed 302-redirects to presigned S3 URLs that embed the bucket access-key id
 *  and endpoint — never let those reach the renderer. */
function sanitizeErrorMessage(msg: string): string {
  return msg.replace(/https?:\/\/\S+/g, '[URL redacted]');
}

export interface UpdateStatus {
  status: 'checking' | 'available' | 'not-available' | 'downloading' | 'downloaded' | 'error';
  info?: UpdateInfo;
  error?: string;
  progress?: { percent: number; bytesPerSecond: number; transferred: number; total: number };
}

export function initAutoUpdater(window: BrowserWindow): void {
  mainWindow = window;

  // app-update.yml is generated by electron-builder. Missing in --dir builds
  // (electron:build:mac:fast) — bail cleanly instead of throwing on every check.
  const resourcesPath = process.resourcesPath ?? path.dirname(app.getAppPath());
  const ymlExists =
    fs.existsSync(path.join(resourcesPath, 'app-update.yml')) ||
    fs.existsSync(path.join(app.getAppPath(), 'app-update.yml'));
  if (!ymlExists) {
    console.warn('[updater] app-update.yml not found — disabled (probably a --dir build)');
    _disabled = true;
    registerUpdaterIpc();
    return;
  }

  autoUpdater.autoDownload = false;
  autoUpdater.autoInstallOnAppQuit = true;

  // NOTE: deliberately do NOT set `autoUpdater.requestHeaders` here. The `.yml`
  // manifest is served by /api/electron/shell with response
  // `Cache-Control: no-store, no-cache, must-revalidate, max-age=0`, which is
  // the authoritative cache directive. A redundant `Cache-Control: no-store`
  // *request* header applied globally (including to the .dmg/.zip binary fetch
  // that 302-redirects to S3) was observed to suppress download-progress
  // events on macOS — clicking Download produced 0% until the file finished,
  // then jumped to 100%. If a stale-manifest bug ever recurs, scope the header
  // to .yml requests via an executor override rather than re-enabling it
  // globally.

  autoUpdater.on('checking-for-update', () => sendStatus({ status: 'checking' }));
  autoUpdater.on('update-available', (info) => sendStatus({ status: 'available', info }));
  autoUpdater.on('update-not-available', (info) =>
    sendStatus({ status: 'not-available', info }),
  );
  autoUpdater.on('download-progress', (progress) =>
    sendStatus({
      status: 'downloading',
      progress: {
        percent: progress.percent,
        bytesPerSecond: progress.bytesPerSecond,
        transferred: progress.transferred,
        total: progress.total,
      },
    }),
  );
  autoUpdater.on('update-downloaded', (info) => sendStatus({ status: 'downloaded', info }));
  autoUpdater.on('error', (err) => sendStatus({ status: 'error', error: err.message }));

  registerUpdaterIpc();

  _periodicInterval = setInterval(() => {
    if (isOffline()) {
      console.log('[updater] periodic check skipped — offline');
      return;
    }
    autoUpdater.checkForUpdates().catch((err) => {
      console.error('[updater] periodic check failed:', err.message);
    });
  }, PERIODIC_CHECK_MS);
}

function sendStatus(status: UpdateStatus): void {
  // Redact presigned-URL leaks from error text before it reaches the renderer.
  const safe: UpdateStatus = status.error
    ? { ...status, error: sanitizeErrorMessage(status.error) }
    : status;
  if (!mainWindow || mainWindow.isDestroyed()) return;
  mainWindow.webContents.send('updater:status', safe);
}

function registerUpdaterIpc(): void {
  ipcMain.handle('updater:check', async () => {
    if (_disabled) return { success: false, error: 'updater disabled (no app-update.yml)' };
    try {
      await autoUpdater.checkForUpdates();
      return { success: true };
    } catch (err) {
      return { success: false, error: err instanceof Error ? err.message : 'check failed' };
    }
  });

  ipcMain.handle('updater:download', async () => {
    if (_disabled) return { success: false, error: 'updater disabled' };
    try {
      await autoUpdater.downloadUpdate();
      return { success: true };
    } catch (err) {
      return { success: false, error: err instanceof Error ? err.message : 'download failed' };
    }
  });

  ipcMain.handle('updater:install', () => {
    if (_disabled) return;
    autoUpdater.quitAndInstall(false, true);
  });

  ipcMain.handle('updater:current-version', () => autoUpdater.currentVersion?.version ?? app.getVersion());
}

/**
 * Startup check with retries — handles transient launch-time network failures.
 */
export async function checkForUpdatesOnStartup(): Promise<void> {
  if (_disabled) return;
  if (isOffline()) {
    console.log('[updater] startup check skipped — offline (will re-check when back online)');
    return;
  }
  for (let attempt = 0; attempt <= RETRY_DELAYS_MS.length; attempt++) {
    try {
      await autoUpdater.checkForUpdates();
      return;
    } catch (err) {
      const msg = err instanceof Error ? err.message : 'unknown';
      console.warn(`[updater] startup check ${attempt + 1} failed: ${msg}`);
      sendStatus({ status: 'error', error: msg });
      if (attempt < RETRY_DELAYS_MS.length) {
        await new Promise((r) => setTimeout(r, RETRY_DELAYS_MS[attempt]));
      }
    }
  }
  console.error('[updater] all startup checks failed — relying on next periodic tick');
}
