/**
 * Electron auto-updater (binary shell).
 *
 * Uses electron-updater's "generic" provider pointing at the Hono server's
 * `/api/electron/shell` endpoint. The Hono route serves `latest-mac.yml` /
 * `.dmg` / `.zip` etc. by 302-redirecting to presigned S3 URLs (see
 * `examples/server-hono/examples/server-hono/server/routes/electron-shell.ts`).
 *
 * Lifecycle:
 *   - autoDownload = false  → user has to confirm via `updater:download` IPC
 *   - autoInstallOnAppQuit = true → applies the downloaded update on next quit
 *   - Periodic re-check every 1h
 *   - Startup check with three retries (10s, 30s, 90s) so a transient
 *     failure on launch doesn't permanently disable updates for that session
 *
 * Renderer side: lib/hooks/useElectronUpdater.ts subscribes to
 * `updater:status` events and exposes the install button to the user.
 */

import { autoUpdater, type UpdateInfo } from 'electron-updater';
import { BrowserWindow, ipcMain, app } from 'electron';
import * as path from 'path';
import * as fs from 'fs';

let mainWindow: BrowserWindow | null = null;
let _periodicInterval: ReturnType<typeof setInterval> | null = null;
let _disabled = false;

const PERIODIC_CHECK_MS = 60 * 60 * 1000;
const RETRY_DELAYS_MS = [10_000, 30_000, 90_000];

export interface UpdateStatus {
  status: 'checking' | 'available' | 'not-available' | 'downloading' | 'downloaded' | 'error';
  info?: UpdateInfo;
  error?: string;
  progress?: { percent: number; bytesPerSecond: number; transferred: number; total: number };
}

export function initAutoUpdater(window: BrowserWindow): void {
  mainWindow = window;

  // app-update.yml is generated by electron-builder. Missing in --dir builds
  // (electron:build:mac:fast) — bail cleanly instead of throwing on every check.
  const resourcesPath = process.resourcesPath ?? path.dirname(app.getAppPath());
  const ymlExists =
    fs.existsSync(path.join(resourcesPath, 'app-update.yml')) ||
    fs.existsSync(path.join(app.getAppPath(), 'app-update.yml'));
  if (!ymlExists) {
    console.warn('[updater] app-update.yml not found — disabled (probably a --dir build)');
    _disabled = true;
    registerUpdaterIpc();
    return;
  }

  autoUpdater.autoDownload = false;
  autoUpdater.autoInstallOnAppQuit = true;
  // Prevent Chromium's HTTP cache from serving stale latest-*.yml.
  autoUpdater.requestHeaders = { 'Cache-Control': 'no-store, no-cache' };

  autoUpdater.on('checking-for-update', () => sendStatus({ status: 'checking' }));
  autoUpdater.on('update-available', (info) => sendStatus({ status: 'available', info }));
  autoUpdater.on('update-not-available', (info) =>
    sendStatus({ status: 'not-available', info }),
  );
  autoUpdater.on('download-progress', (progress) =>
    sendStatus({
      status: 'downloading',
      progress: {
        percent: progress.percent,
        bytesPerSecond: progress.bytesPerSecond,
        transferred: progress.transferred,
        total: progress.total,
      },
    }),
  );
  autoUpdater.on('update-downloaded', (info) => sendStatus({ status: 'downloaded', info }));
  autoUpdater.on('error', (err) => sendStatus({ status: 'error', error: err.message }));

  registerUpdaterIpc();

  _periodicInterval = setInterval(() => {
    autoUpdater.checkForUpdates().catch((err) => {
      console.error('[updater] periodic check failed:', err.message);
    });
  }, PERIODIC_CHECK_MS);
}

function sendStatus(status: UpdateStatus): void {
  if (!mainWindow || mainWindow.isDestroyed()) return;
  mainWindow.webContents.send('updater:status', status);
}

function registerUpdaterIpc(): void {
  ipcMain.handle('updater:check', async () => {
    if (_disabled) return { success: false, error: 'updater disabled (no app-update.yml)' };
    try {
      await autoUpdater.checkForUpdates();
      return { success: true };
    } catch (err) {
      return { success: false, error: err instanceof Error ? err.message : 'check failed' };
    }
  });

  ipcMain.handle('updater:download', async () => {
    if (_disabled) return { success: false, error: 'updater disabled' };
    try {
      await autoUpdater.downloadUpdate();
      return { success: true };
    } catch (err) {
      return { success: false, error: err instanceof Error ? err.message : 'download failed' };
    }
  });

  ipcMain.handle('updater:install', () => {
    if (_disabled) return;
    autoUpdater.quitAndInstall(false, true);
  });

  ipcMain.handle('updater:current-version', () => autoUpdater.currentVersion?.version ?? app.getVersion());
}

/**
 * Startup check with retries — handles transient launch-time network failures.
 */
export async function checkForUpdatesOnStartup(): Promise<void> {
  if (_disabled) return;
  for (let attempt = 0; attempt <= RETRY_DELAYS_MS.length; attempt++) {
    try {
      await autoUpdater.checkForUpdates();
      return;
    } catch (err) {
      const msg = err instanceof Error ? err.message : 'unknown';
      console.warn(`[updater] startup check ${attempt + 1} failed: ${msg}`);
      sendStatus({ status: 'error', error: msg });
      if (attempt < RETRY_DELAYS_MS.length) {
        await new Promise((r) => setTimeout(r, RETRY_DELAYS_MS[attempt]));
      }
    }
  }
  console.error('[updater] all startup checks failed — relying on next periodic tick');
}
