/**
 * Org-scoped Electric collection factory.
 *
 * Wraps @tanstack/electric-db-collection with the boilerplate-specific
 * concerns:
 *   - point Electric at the proxy URL (lib/electric/tables.ts)
 *   - send X-Org-Id + Bearer auth headers on every shape request
 *   - route mutations through the WAL on native, plain apiFetch on web
 *   - handle the Electric "must-refetch" 409 + 401 token refresh + stale-cache
 *     errors (the SDK surfaces these via onError; we decide whether to retry,
 *     stop the stream, or trigger a full resync)
 *
 * To create a new collection, call createOrgScopedCollection<RowType>({
 *   table, schema, onInsert, onUpdate, onDelete, getInsertWalParams, ...
 * }) — see collections/notes.ts for the canonical example.
 */

import { createCollection } from '@tanstack/react-db';
import { electricCollectionOptions } from '@tanstack/electric-db-collection';
import { FetchError } from '@electric-sql/client';
import type { z } from 'zod';
import { getElectricProxyUrl } from '../proxy-url';
import { getCurrentOrgId } from '@/lib/contexts/OrgContext';
import { apiFetchViaWal } from '../mutation-wal';
import { createClient as createSupabaseClient } from '@/lib/supabase/client';

// ---------------------------------------------------------------------------
// Persistence-loading flag
//
// While the persistence layer restores cached items via collection.insert(),
// TanStack DB still fires onInsert for each row. Without this guard every
// cached item would be re-POSTed to the server on every app start.
// ---------------------------------------------------------------------------

let _isPersistenceLoading = false;
export function setIsPersistenceLoading(value: boolean): void {
  _isPersistenceLoading = value;
}

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface BaseRow {
  id: string;
  [key: string]: unknown;
}

export interface WalParams {
  endpoint: string;
  method: 'POST' | 'PATCH' | 'PUT' | 'DELETE';
  body: Record<string, unknown> | null;
}

export interface CollectionConfig<TRow extends BaseRow> {
  /** Postgres table name (also used as the collection id and shape param). */
  table: string;
  /** Zod schema for each row. Generated by scripts/generate-electric-schemas.ts. */
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  schema: z.ZodObject<any>;
  /** Insert handler — usually proxied through getInsertWalParams. */
  onInsert: (row: TRow) => Promise<void>;
  onUpdate: (original: TRow, changes: Partial<TRow>) => Promise<void>;
  onDelete: (row: TRow) => Promise<void>;
  /** WAL metadata for offline-first inserts. */
  getInsertWalParams?: (row: TRow) => WalParams;
  getUpdateWalParams?: (original: TRow, changes: Partial<TRow>) => WalParams;
  getDeleteWalParams?: (row: TRow) => WalParams;
}

// ---------------------------------------------------------------------------
// Header helpers
// ---------------------------------------------------------------------------

function getOrgIdHeader(): string {
  if (typeof window === 'undefined') return '';
  return getCurrentOrgId() ?? '';
}

/**
 * On native (Capacitor/Electron) the renderer loads from a different origin
 * than the API, so cookies aren't sent automatically. Electric calls this
 * function on every shape request to attach a fresh Bearer token.
 */
async function getAuthHeader(): Promise<string> {
  if (typeof window === 'undefined') return '';
  try {
    const supabase = createSupabaseClient();
    const { data } = await supabase.auth.getSession();
    if (data.session?.access_token) return `Bearer ${data.session.access_token}`;
  } catch {
    /* supabase not configured yet */
  }
  return '';
}

// ---------------------------------------------------------------------------
// Factory
// ---------------------------------------------------------------------------

export function createOrgScopedCollection<TRow extends BaseRow>(
  config: CollectionConfig<TRow>,
) {
  return createCollection(
    electricCollectionOptions({
      id: config.table,
      schema: config.schema,
      getKey: (item) => (item as BaseRow).id,

      shapeOptions: {
        url: getElectricProxyUrl(),
        // _org makes the URL org-specific so HTTP caches don't serve stale
        // cross-org data. The proxy ignores it.
        params: { table: config.table, _org: () => getCurrentOrgId() ?? '' },
        headers: {
          'X-Org-Id': getOrgIdHeader,
          Authorization: getAuthHeader,
        },
        onError: async (error: Error) => {
          if (error instanceof FetchError) {
            if (error.status === 403) {
              // Permission denied (wrong org or membership revoked). Token
              // refresh won't help — stop the stream. The provider will
              // recreate it after the next org change or sign-in.
              console.warn(`[electric] 403 on "${config.table}" — stopping (permission)`);
              return;
            }
            if (error.status === 401) {
              // Expired token. Trigger a refresh; on success ask the SDK to
              // retry (return {} = retry with backoff).
              const supabase = createSupabaseClient();
              const { error: refreshErr } = await supabase.auth.refreshSession();
              if (!refreshErr) {
                console.log(`[electric] token refreshed for "${config.table}"`);
                return {};
              }
              console.warn(`[electric] refresh failed for "${config.table}" — stopping`);
              return;
            }
            if (error.status === 409) {
              // Stale shape handle — happens during org switches. The provider
              // recreates collections after the switch; this stream just stops.
              console.warn(`[electric] 409 on "${config.table}" — stale handle, stopping`);
              return;
            }
          }

          const isStaleCache =
            error.message.includes('stale cached response') ||
            error.message.includes('CDN continues serving');

          console.error(`[electric] sync error on "${config.table}":`, error.message);

          if (isStaleCache) {
            // SDK's cache-buster retries are exhausted. Trigger a full resync.
            console.error(
              `[electric] persistent stale cache on "${config.table}" — full resync`,
            );
            setTimeout(async () => {
              try {
                // Dynamic import avoids a circular dep at module-init
                // (TanStackDbProvider → collections → factory). The build
                // warns this won't split chunks; that's expected and OK.
                const { forceResync } = await import('../TanStackDbProvider');
                await forceResync();
              } catch (e) {
                console.error('[electric] forceResync failed:', e);
                window.location.reload();
              }
            }, 2000);
            return;
          }

          // Default: ask SDK to retry with internal backoff.
          return {};
        },
      },

      onInsert: async ({ transaction }) => {
        if (_isPersistenceLoading) return;
        const row = transaction.mutations[0].modified as TRow;
        if (config.getInsertWalParams) {
          const w = config.getInsertWalParams(row);
          await apiFetchViaWal(
            w.endpoint,
            {
              method: w.method,
              headers: { 'Content-Type': 'application/json' },
              ...(w.body && { body: JSON.stringify(w.body) }),
            },
            { table: config.table, type: 'insert', entityId: row.id },
          );
        } else {
          await config.onInsert(row);
        }
      },

      onUpdate: async ({ transaction }) => {
        if (_isPersistenceLoading) return;
        const { original, changes } = transaction.mutations[0];
        const orig = original as TRow;
        const ch = changes as Partial<TRow>;
        if (config.getUpdateWalParams) {
          const w = config.getUpdateWalParams(orig, ch);
          await apiFetchViaWal(
            w.endpoint,
            {
              method: w.method,
              headers: { 'Content-Type': 'application/json' },
              ...(w.body && { body: JSON.stringify(w.body) }),
            },
            { table: config.table, type: 'update', entityId: orig.id },
          );
        } else {
          await config.onUpdate(orig, ch);
        }
      },

      onDelete: async ({ transaction }) => {
        if (_isPersistenceLoading) return;
        const row = transaction.mutations[0].original as TRow;
        if (config.getDeleteWalParams) {
          const w = config.getDeleteWalParams(row);
          await apiFetchViaWal(
            w.endpoint,
            {
              method: w.method,
              ...(w.body && {
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(w.body),
              }),
            },
            { table: config.table, type: 'delete', entityId: row.id },
          );
        } else {
          await config.onDelete(row);
        }
      },
    }),
  );
}
