/**
 * Org-scoped sync collection factory.
 *
 * Wraps `@tanstack/react-db`'s `createCollection` with:
 *   - `@tanstack/query-db-collection` for the read path — collections fetch
 *     from `GET /api/sync/:table` and TanStack Query owns the cache. The
 *     broadcast listener (`lib/realtime/broadcast-listener.tsx`) invalidates
 *     the matching query key when a remote `change` event arrives.
 *   - `@tanstack/browser-db-sqlite-persistence` for offline persistence — rows
 *     survive reload via OPFS-backed wa-sqlite on web/Electron and via the
 *     Capacitor SQLite adapter on iOS/Android. The persistence handle is
 *     opened once per user session by `TanStackDbProvider` and shared across
 *     collections through `setPersistence` below.
 *
 * Mutation handlers (`onInsert`/`onUpdate`/`onDelete`) exist for the
 * direct-write fallback path — in practice the offline executor in
 * `../offline-executor.ts` intercepts mutations and routes them through
 * its outbox so writes survive reconnect, app restart, and 409 conflicts.
 *
 * To add a new collection, see `./notes.ts` for the canonical shape.
 */

import { createCollection } from '@tanstack/react-db';
import { queryCollectionOptions } from '@tanstack/query-db-collection';
// Re-exported `persistedCollectionOptions` keeps us off the internal
// `@tanstack/db-sqlite-persistence-core` package; same for `Collection`
// via `@tanstack/react-db`. One declared TanStack DB surface per concern.
import {
  persistedCollectionOptions,
  type PersistedCollectionPersistence,
} from '@tanstack/browser-db-sqlite-persistence';
import type { Collection } from '@tanstack/react-db';
import { z } from 'zod';
import { getCurrentOrgId } from '@/lib/contexts/OrgContext';
import { apiFetch } from '@/lib/api-client';
import { queryClient } from '@/lib/query-client';

/**
 * Shared SQLite persistence handle. Set once per user session by
 * `TanStackDbProvider` after `openBrowserWASQLiteOPFSDatabase` /
 * `createCapacitorSQLitePersistence` resolves. All org-scoped collections
 * created during that session share the same handle and live in one
 * underlying .db file; org compartmentalisation happens via per-org
 * collection IDs.
 */
let _persistence: PersistedCollectionPersistence | null = null;

export function setPersistence(persistence: PersistedCollectionPersistence | null): void {
  _persistence = persistence;
}

/** Bump when the persisted row shape for any collection changes incompatibly.
 *  The adapter uses this to decide whether to drop and rebuild a collection's
 *  SQLite table on app start. One value for the whole app — collections
 *  evolve together. */
const SCHEMA_VERSION = 1;

interface BaseRow {
  id: string;
  [key: string]: unknown;
}

/**
 * Config passed to `createOrgScopedCollection`. The fallback mutation
 * handlers are invoked when a row is inserted via `collection.insert(row)`
 * outside an offline-executor action — wire them to plain `apiFetch` calls.
 */
export interface CollectionConfig<TRow extends BaseRow> {
  /** Postgres table name. Also used as the collection ID prefix. */
  table: string;
  /** Zod schema for row validation. Generated by `scripts/generate-schemas.ts`. */
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  schema: z.ZodObject<any>;
  /** Handle an insert mutation (direct-write fallback). */
  onInsert: (modified: TRow) => Promise<void>;
  /** Handle an update mutation (direct-write fallback). */
  onUpdate: (original: TRow, changes: Partial<TRow>) => Promise<void>;
  /** Handle a delete mutation (direct-write fallback). */
  onDelete: (original: TRow) => Promise<void>;
}

/**
 * Create an org-scoped sync collection.
 *
 * Collection ID is `${table}-${orgId}` so each org gets its own SQLite
 * table. On org switch the provider tears down + recreates collections
 * (via orgVersion increment); the new collection picks up a fresh table
 * and the previous org's data stays inert until logout-time DB cleanup.
 */
export function createOrgScopedCollection<TRow extends BaseRow>(
  config: CollectionConfig<TRow>,
) {
  const orgId = getCurrentOrgId();
  if (!orgId) {
    throw new Error(
      `[sync] createOrgScopedCollection("${config.table}") called without an active org — provider gates on orgReady`,
    );
  }

  const collectionId = `${config.table}-${orgId}`;

  // Schema is intentionally omitted from queryCollectionOptions: the
  // /api/sync/:table endpoint returns server-validated rows, and the
  // typed-schema overload demands an explicit `select` we don't need.
  // Row shape is enforced via the TRow generic on the queryFn return type.
  const queryOptions = queryCollectionOptions<TRow>({
    id: collectionId,
    getKey: (item) => item.id,
    // Scope key included so org switches and user switches produce distinct
    // cache entries — TanStack Query garbage-collects the old key naturally.
    queryKey: [config.table, orgId],
    queryFn: () => apiFetch<TRow[]>(`/api/sync/${config.table}`),
    queryClient,
    onInsert: async ({ transaction }) => {
      const row = transaction.mutations[0].modified as TRow;
      await config.onInsert(row);
    },
    onUpdate: async ({ transaction }) => {
      const { original, changes } = transaction.mutations[0];
      await config.onUpdate(original as TRow, changes as Partial<TRow>);
    },
    onDelete: async ({ transaction }) => {
      const row = transaction.mutations[0].original as TRow;
      await config.onDelete(row);
    },
  });

  // When persistence is null (OPFS open timed out, browser without OPFS,
  // private browsing) we skip the persistedCollectionOptions wrap and run
  // memory-only. Queries still flow data through; nothing is cached to
  // SQLite between sessions.
  if (!_persistence) {
    return createCollection(
      queryOptions as unknown as Parameters<typeof createCollection>[0],
    ) as unknown as Collection<TRow, string | number>;
  }

  const persistedOptions = persistedCollectionOptions({
    ...queryOptions,
    persistence: _persistence,
    schemaVersion: SCHEMA_VERSION,
  });

  return createCollection(
    persistedOptions as unknown as Parameters<typeof createCollection>[0],
  ) as unknown as Collection<TRow, string | number>;
}
