#!/usr/bin/env node
/**
 * Codegen: read DbX interfaces from lib/db/types/ and emit Zod schemas to
 * lib/sync/collections/generated/.
 *
 * The minimal version below targets one table (notes). Extend the TABLES
 * array as you add tables. A more sophisticated version would walk
 * lib/db/types/ via the TypeScript compiler API and emit whatever DbX
 * interfaces it finds — left as an exercise once you outgrow the manual list.
 *
 * Usage:
 *   npx tsx scripts/generate-schemas.ts
 */

import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';

const ROOT = join(__dirname, '..');
const OUT_DIR = join(ROOT, 'lib/sync/collections/generated');

interface FieldSpec {
  name: string;
  zod: string;
}

interface TableSpec {
  fileName: string;     // e.g. 'note.generated.ts'
  exportPrefix: string; // e.g. 'dbNote' → dbNoteRowSchema, DbNoteRow
  fields: FieldSpec[];
}

const TABLES: TableSpec[] = [
  {
    fileName: 'note.generated.ts',
    exportPrefix: 'dbNote',
    fields: [
      { name: 'id', zod: 'z.string()' },
      { name: 'org_id', zod: 'z.string()' },
      { name: 'user_id', zod: 'z.string()' },
      { name: 'title', zod: 'z.string()' },
      { name: 'body', zod: 'z.string()' },
      { name: 'created_at', zod: 'z.string()' },
      { name: 'updated_at', zod: 'z.string()' },
      { name: 'deleted_at', zod: 'z.string().nullish()' },
    ],
  },
];

function emitSchema(spec: TableSpec): string {
  const typeName = spec.exportPrefix.charAt(0).toUpperCase() + spec.exportPrefix.slice(1) + 'Row';
  const schemaName = `${spec.exportPrefix}RowSchema`;
  const fields = spec.fields.map((f) => `  ${f.name}: ${f.zod},`).join('\n');
  return `/**
 * Generated by scripts/generate-schemas.ts. Do not edit by hand.
 * @public
 */

import { z } from 'zod';

export const ${schemaName} = z.object({
${fields}
});

export type ${typeName} = z.infer<typeof ${schemaName}>;
`;
}

mkdirSync(OUT_DIR, { recursive: true });

for (const t of TABLES) {
  const out = join(OUT_DIR, t.fileName);
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, emitSchema(t));
  console.log(`✓ wrote ${t.fileName}`);
}

const indexLines = TABLES.map((t) => `export * from './${t.fileName.replace(/\.ts$/, '')}';`);
writeFileSync(join(OUT_DIR, 'index.ts'), `/** @public */\n${indexLines.join('\n')}\n`);
console.log('✓ wrote index.ts');
